class SubmissionFile:
    """A student submitted file

    This object provides simple, read-only properties which represent the
    various important parts and the whole of the filename that was generated by
    BBLearn including: the username, the date submitted, and the name of the
    file as submitted.

    """

    @classmethod
    def from_bblearn_filename(cls, filename):
        from .bblearn import filename
        return cls(**filename.segment(filename))


    def __init__(self, submitted_as, submitted_by, submitted_for, submitted_on):
        self.__submitted_as = submitted_as
        self.__submitted_by = submitted_by
        self.__submitted_for = submitted_for
        self.__submitted_on = submitted_on


    def __str__(self):
        return self.name


    def __repr__(self):
        return f"BBLearnFilename('{self}')"


    @property
    def bblearn_name(self):
        """The filename generated by BBLearn from the name as submitted"""
        return "_".join([self.submitted_for, self.submitted_by, 'attempt',
                         self.submitted_on, self.submitted_as])


    @property
    def submitted_as(self):
        """The filename minus BBLearn's add-ons"""
        return self.__submitted_as


    @property
    def submitted_by(self):
        """The username of the student who submitted the file"""
        return self.__submitted_by


    @property
    def submitted_on(self):
        """The timestamp for the submission attempt the file is from"""
        return self.__submitted_on


    @property
    def submitted_for(self):
        """The BBLearn assignment the file was submitted in response to"""
        return self.__submitted_for
